services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab1-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/lab1
      DB_USERNAME: lab1
      DB_PASSWORD: lab1
    ports:
      - "127.0.0.1:26125:26125"
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: lab1-postgres
    environment:
      POSTGRES_DB: lab1
      POSTGRES_USER: lab1
      POSTGRES_PASSWORD: lab1
    ports:
      - "6262:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lab1 -d lab1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
