spring.application.name=lab1-app
server.port=26125
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jackson.default-property-inclusion=non_null
app.timers.fixed-delay-ms=30000
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
app.security.jwt.secret=${APP_JWT_SECRET:change-this-jwt-secret-for-production}
app.security.jwt.ttl-seconds=${APP_JWT_TTL_SECONDS:3600}
app.security.bootstrap.moderator.enabled=${APP_BASE_MODERATOR_ENABLED:true}
app.security.bootstrap.moderator.username=${APP_BASE_MODERATOR_USERNAME:moderator}
app.security.bootstrap.moderator.password=${APP_BASE_MODERATOR_PASSWORD:moderator}

server.forward-headers-strategy=framework
app.atomikos.default-jta-timeout-seconds=60
app.atomikos.datasource.unique-resource-name=lab1DataSource
app.atomikos.datasource.min-pool-size=1
app.atomikos.datasource.max-pool-size=10
app.atomikos.datasource.borrow-connection-timeout=30
app.atomikos.datasource.xa-data-source-class-name=org.postgresql.xa.PGXADataSource
app.atomikos.datasource.xa-properties.URL=${DB_URL:jdbc:postgresql://localhost:6262/lab1}
app.atomikos.datasource.xa-properties.user=${DB_USERNAME:lab1}
app.atomikos.datasource.xa-properties.password=${DB_PASSWORD:lab1}
#app.yookassa.enabled=${YOOKASSA_ENABLED:false}
#app.yookassa.api-url=${YOOKASSA_API_URL:https://api.yookassa.ru/v3}
#app.yookassa.shop-id=${YOOKASSA_SHOP_ID:}
#app.yookassa.secret-key=${YOOKASSA_SECRET_KEY:}
#app.yookassa.return-url=${YOOKASSA_RETURN_URL:https://www.youtube.com/watch?v=dQw4w9WgXcQ}
app.yookassa.enabled=${YOOKASSA_ENABLED:true}
app.yookassa.api-url=${YOOKASSA_API_URL:https://api.yookassa.ru/v3}
app.yookassa.shop-id=${YOOKASSA_SHOP_ID:1289866}
app.yookassa.secret-key=${YOOKASSA_SECRET_KEY:test_tXwtHDF4gcuW3Nu3ZLMVQqC9NLOb9mg6QzNTKei7SPo}
app.yookassa.return-url=${YOOKASSA_RETURN_URL:https://www.youtube.com/watch?v=dQw4w9WgXcQ}
