package ifmo.se.lab1app.campaign.model;

public enum CampaignEventType {
    CAMPAIGN_CREATED,
    CAMPAIGN_CONFIGURED,
    CREATIVES_UPLOADED,
    SUBMITTED_FOR_CHECK,
    AUTO_VALIDATION_PASSED,
    AUTO_VALIDATION_FAILED,
    VALIDATION_ISSUES_FIXED,
    MODERATION_APPROVED,
    MODERATION_REJECTED,
    MODERATION_ISSUES_FIXED,
    INVOICE_CREATED,
    INVOICE_PAID,
    INVOICE_OVERDUE,
    WAITING_START,
    CAMPAIGN_ACTIVATED,
    PAUSE_REQUESTED,
    CAMPAIGN_PAUSED,
    RESUME_REQUESTED,
    BUDGET_NOT_FORMED,
    BUDGET_FORMED,
    CAMPAIGN_STOPPED,
    CAMPAIGN_FROZEN,
    BUDGET_EXHAUSTED,
    END_AT_REACHED,
    TIMERS_PROCESSED
}
