package ifmo.se.lab1app.campaign.model;

public enum CampaignStatus {
    DRAFT,
    CONFIGURED,
    CREATIVES_UPLOADED,
    SUBMITTED_FOR_CHECK,
    VALIDATION_FAILED,
    ON_MODERATION,
    MODERATION_REJECTED,
    WAITING_PAYMENT,
    WAITING_START,
    ACTIVE,
    PAUSED,
    FROZEN_NO_PAYMENT,
    STOPPED
}
